server:
  port: 10010
spring:
  application:
    name: shop-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins:
            - "http://manage.leyou.com"
          allowedHeaders:
            - "*"
          allowCredentials: true
          maxAge: 360000
          allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
            - OPTIONS
            - HEAD
      default-filters:
        - name: Hystrix
          args:
            name: fallback
            fallbackUri: forward:/fallback
      routes:
        - id: shop-item # 路由id,随意写
          uri: lb://shop-item #代理的服务地址: lb代表负载均衡(从nacos中获取具体服务)
          predicates: # 路由断言,可以配置映射路径
            - Path=/api/item/**
          filters: # 表示过滤1个路径,2表示两个路径,一次类推
            - stripPrefix=2
        - id: shop-upload  # 路由id,随意写
            uri: lb://shop-upload #代理的服务地址: lb代表负载均衡(从nacos中获取具体服务)
            predicates: # 路由断言,可以配置映射路径
              - Path=/api/upload/**
            filters: # 表示过滤1个路径,2表示两个路径,一次类推
              - stripPrefix=2


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #设置API网关中路由转发请求的HystrixCommand执行超时时间
            timeoutInMilliseconds: 5000
